name: Trivy Scan
description: Scan filesystem and optionally a container image
inputs:
  image-ref:
    required: false
    description: Image reference to scan (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/app:tag)
  severity:
    required: false
    default: CRITICAL,HIGH
  exit-code:
    required: false
    default: '1'
runs:
  using: composite
  steps:
    - name: Trivy FS scan (source)
      uses: aquasecurity/trivy-action@0.24.0
      with:
        scan-type: fs
        format: table
        severity: ${{ inputs.severity }}
        exit-code: ${{ inputs.exit-code }}
        ignore-unfixed: true

    - name: Trivy Image scan
      if: ${{ inputs.image-ref != '' }}
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: ${{ inputs.image-ref }}
        format: table
        severity: ${{ inputs.severity }}
        exit-code: ${{ inputs.exit-code }}
        ignore-unfixed: true
